name: CI con Maven y Doxygen

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configurar JDK 20
      uses: actions/setup-java@v2
      with:
        java-version: '20'
        distribution: 'adopt'   
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: '8.0'
    - name: Crear la base de datos 'doctorclick'
      run: mysql -uroot -h127.0.0.1 < src/sql/init.sql  
    - name: Compilar el código
      run: mvn clean compile
    - name: Testing
      run: mvn test
    - name: Instalar doxygen
      run: sudo apt-get install -y doxygen
    - name: Instalar graphviz
      run: sudo apt-get install -y graphviz
    - name: Generar documentación con doxygen
      run: mvn doxygen:report
    - name: Generar documentacion de covertura de tests con Jacoco
      run: mvn jacoco:report
    - name: Configurar ficheros para GitHub pages
      run: |
          mkdir -p gh-pages/doxygen
          mkdir -p gh-pages/jacoco
          cp -r target/doxygen/html/** gh-pages/doxygen/
          cp -r target/site/jacoco/** gh-pages/jacoco/
          cp .github/ghpages.index.html gh-pages/index.html
          cp -r .github/img gh-pages/
    - name: Publicar en GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.3.0
      with:
        build_dir: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
